name: parcialclinicafirebase
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.2.1
  cloud_firestore: ^2.2.1
  rxdart: ^0.27.1
  http: ^0.13.3
  shared_preferences:
  dropdownfield: ^1.0.3
  date_format: ^2.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/backgroundDrawer.jpg
    - assets/menu-img.jpg
    - assets/loginappmovil.png

        
    
    
                                      